#!/bin/sh
#deploy="false"
deploy="true"

image=NeverNote
version=1.0-SNAPSHOT
latest=true

#OPTIONS="--no-cache --force-rm"
#OPTIONS="--no-cache"
#OPTIONS="--force-rm"
OPTIONS=""

docker build ${OPTIONS} -t vrpala17/${image}:1.0-SNAPSHOT .
if [ "$?" -eq 0 ] && [ ${deploy} == "true" ]; then
    docker push vrpala17/${image}:1.0-SNAPSHOT
    if [ "$latest" == "true" ]; then
        docker tag vrpala17/${image}:1.0-SNAPSHOT vrpala17/${image}:latest
        docker push vrpala17/${image}:latest
    fi
fi
